bpf: Use div64_u64{,_rem}() in scev.c
For whatever reason gcc built-ins implementing 64-bit division are not
wired into 32-bit kernel builds:

   ld: kernel/bpf/scev.c:2074:(.text+0x4512): undefined reference to `__udivdi3'
   ld: kernel/bpf/scev.c:2141:(.text+0x475b): undefined reference to `__udivmoddi4'

Instead, one has to use div64_u64() and div64_u64_rem() explicitly.

Fixes: 6ccf49f79327 ("bpf: Use SCEV to widen bounded loops")
Reported-by: Tejun Heo <tj@kernel.org>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Eduard Zingerman <eddyz87@gmail.com>
Link: https://lore.kernel.org/bpf/20261010205828.3366892-1-eddyz87@gmail.com
Signed-off-by: Kumar Kartikeya Dwivedi <memxor@gmail.com>